version: '2'

volumes:
  fcrepo:
  solr:
  db:
  redis:
  zk1:
  zk2:
  zk3:
  zkconf:
  app:
  certs:
  certs-data:
  self-signed:

networks:
  external:
  internal:

services:
  zoo1:
    image: zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk1:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster
  zoo2:
    image: zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk2:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster
  zoo3:
    image: zookeeper
    restart: always
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    expose:
      - 2181
      - 2888
      - 3888
    volumes:
      - zk3:/data
      - zkconf:/conf
    networks:
      internal:
       aliases:
         - zookeeper_cluster

  solr:
    image: solr
    command: solr -c -f -z zookeeper_cluster:2181
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    expose:
      - 8983
    volumes:
      - .:/app
      - solr:/opt/solr/server/solr
    networks:
      internal:

  fcrepo:
    image: cbeer/fcrepo4:4.7
    expose:
      - 8080
    volumes:
      - fcrepo:/data
    environment:
      - JAVA_OPTS=${JAVA_OPTS} -Dfcrepo.modeshape.configuration="classpath:/config/file-simple/repository.json" -Dfcrepo.object.directory="/data/objects" -Dfcrepo.binary.directory="/data/binaries"
    networks:
      internal:

  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      internal:

  app:
    build: .
    environment:
      - REDIS_HOST=redis
      - DATABASE_URL=postgresql://postgres@db/postgres
      - FEDORA_URL=http://fcrepo:8080/fcrepo/rest
      - SOLR_URL=http://solr:8983/solr/
      - SETTINGS__ACTIVE_JOB__QUEUE_ADAPTER=sidekiq
      - SETTINGS__MULTITENANCY__ADMIN_ONLY_TENANT_CREATION=false
      - SETTINGS__SOLR__URL=http://solr:8983/solr/
      - SETTINGS__ZOOKEEPER__CONNECTION_STR=zookeeper_cluster:2181/configs
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=false
      - RAILS_LOG_TO_STDOUT=true
      - SECRET_KEY_BASE=asdf
      - RAILS_CACHE_STORE_URL=memcache
      # version and location of fits are set in Dockerfile:
      - LD_LIBRARY_PATH=/opt/fits-1.0.5/tools/mediainfo/linux
    volumes:
      - app:/data/tmp/uploads
    networks:
      internal:

  web:
    extends:
      service: app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec puma -C config/puma.rb"
    depends_on:
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - zoo2
      - zoo3
      - memcache
      - db_migrate
    expose:
      - 3000
    networks:
      external:
      internal:

  workers:
    extends:
      service: app
    command: bundle exec sidekiq
    environment:
      - SETTINGS__FITS_PATH=/opt/fits-1.0.5/fits.sh
    depends_on:
      - db
      - solr
      - fcrepo
      - redis
      - zoo1
      - zoo2
      - zoo3
      - initialize_app
      - db_migrate

  initialize_app:
    extends:
      service: app
    restart: on-failure
    command: bundle exec rails zookeeper:upload
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  db_migrate:
    extends:
      service: app
    restart: on-failure
    command: bundle exec rails db:migrate
    depends_on:
      - db

  web_server:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    links:
      - web
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    networks:
      internal:
      external:
    volumes:
      - self-signed:/etc/selfsigned
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt

  get_cert:
    # image: certbot/certbot
    # command: "certonly -n --agree-tos --email hyku@digitalnest.co.uk --no-eff-email --keep --test-cert --webroot --webroot-path=/data/letsencrypt -d 'up2.digitalnest.co.uk,repo1.up2.digitalnest.co.uk,repo2.up2.digitalnest.co.uk' --post-hook '/tmp/cert_create_status.sh'"
    build:
      context: .
      dockerfile: ./certbot/Dockerfile
    # TODO : Add cron to renew certificate and restart nginx
    depends_on:
      - web_server
    networks:
      internal:
      external:
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - ${PWD}/nginx/cert_create_status.sh:/tmp/cert_create_status.sh

  cert_manager:
    build:
      context: .
      dockerfile: ./nginx/cert-manager-Dockerfile
    depends_on:
      - get_cert
    privileged: true
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock

  redis:
    image: redis:3
    command: redis-server
    volumes:
      - redis:/data
    networks:
      internal:

  memcache:
    image: memcached
    networks:
      internal:
